import socket
import base64
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(('poczta.interia.pl', 587))
print(s.recv(1024))
s.send(b'EHLO ggg\r\n')
print(s.recv(1024))
s.send(b'AUTH LOGIN\r\n')
print(s.recv(1024))
log = base64.b64encode(b'pas2017@interia.pl')
s.send(log + b'\r\n')
print(s.recv(1024))
h = base64.b64encode(b'P4SInf2017')
s.send(h + b'\r\n')
print(s.recv(1024))
od = input('od: ')
do = input('do: ')
tyt = input('tyt: ')
tekst = input('tekst: ')
s.send(b'MAIL FROM: <' + od.encode() + b'>\r\n')
print(s.recv(1024))
s.send(b'RCPT TO: <' + do.encode() + b'>\r\n')
print(s.recv(1024))
s.send(b'DATA\r\n')
print(s.recv(1024))
w = f'From: {od}\r\nTo: {do}\r\nSubject: {tyt}\r\n\r\n{tekst}\r\n.\r\n'
s.send(w.encode())
print(s.recv(1024))
s.send(b'QUIT\r\n')
print(s.recv(1024))
